# Generated by Django 6.0.2 on 2026-03-31 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_activity', models.CharField(choices=[('CONSISTENT', 'Very Consistent'), ('MODERATE', 'Fairly Regular'), ('FLUNCTUATING', 'Flunctuating')], default='CONSISTENT', max_length=30)),
                ('user_type', models.CharField(choices=[('INDIVIDUAL', 'individual'), ('ENTREPRENEUR', 'entrepreneur')], default='INDIVIDUAL', max_length=20)),
                ('country', models.CharField(max_length=30, null=True)),
                ('state', models.CharField(max_length=30, null=True)),
                ('city', models.CharField(max_length=30, null=True)),
                ('currency', models.CharField(default='$', max_length=10)),
                ('contact', models.CharField(max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('summary_statistics', models.JSONField(default=None, null=True)),
                ('number_of_transactions', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-user_id'], name='account_pro_user_id_251fe9_idx')],
            },
        ),
    ]
