# Generated by Django 6.0.2 on 2026-08-22 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='currency',
            field=models.CharField(blank=True, default='$', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='financial_activity',
            field=models.CharField(blank=True, choices=[('CONSISTENT', 'Very Consistent'), ('MODERATE', 'Fairly Regular'), ('FLUNCTUATING', 'Flunctuating')], default='CONSISTENT', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='number_of_transactions',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='summary_statistics',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('INDIVIDUAL', 'individual'), ('ENTREPRENEUR', 'entrepreneur')], default='INDIVIDUAL', max_length=20),
        ),
    ]
