"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
from dotenv import load_dotenv
from pathlib import Path
import dj_database_url
import os


# making the env variables accessible
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0hqt4e6h-dv0liu0drpx)^#t4p+)gkobii9-1&%@yi43#3^xwf'

debug_env = True if os.environ.get("DEBUG")  == "Yes" else False

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = debug_env

# Read ALLOWED_HOSTS from Render environment variables, fallback to localhost for development
ALLOWED_HOSTS = ["*"]
# ALLOWED_HOSTS = [
#     os.environ.get("ALLOWED_HOST"), 
#     '127.0.0.1',                   # 🚀 Add this: Render's internal routing IP
#     'localhost',     ]


# Application definition

CUSTOM_APPS = [
    "account",
    "transaction",
    "ml",
    "media_app"
]
THIRD_PARTY_APPS = [
    "corsheaders",
    "rest_framework",
    "rest_framework.authtoken",
    "django_filters",
    "drf_spectacular",
    "storages",
    'django_extensions'
]
DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

]
INSTALLED_APPS =  DJANGO_APPS + THIRD_PARTY_APPS + CUSTOM_APPS


MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
   os.environ.get("CLIENT_URL"),
   "http://localhost:5000",
    "http://127.0.0.1:5000",
]

# Tells Django to trust Render's reverse proxy header for secure connections
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True

CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = [
    "https://onrender.com",
    "https://vercel.app",
   os.environ.get("CLIENT_URL"),
   "http://localhost:5000",
    "http://127.0.0.1:5000",
]


ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

dev_db = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # },
    "default":{
        "ENGINE":"django.db.backends.postgresql",
        "NAME":"finguard",
        "USER":"postgres",
        "PASSWORD":782800,
        "HOST":"localhost",
        "PORT":"5432"
    }
}
prod_db = {
    "default": dj_database_url.config(
        default=os.getenv("DB_URL"),
        conn_max_age=0,
        ssl_require=True
    )
}
# DATABASES =  prod_db
DATABASES = dev_db if debug_env else prod_db

# 
# 
# LEGACY
# 
# 

# CELERY CONFIGURATION
# CELERY_BROKER_URL = os.environ.get(
#     'CELERY_BROKER_URL', 
#     'amqp://guest:guest@localhost:5672//'
# )

# # Optional project stability configs
# CELERY_ACCEPT_CONTENT = ['json']
# CELERY_TASK_SERIALIZER = 'json'
# CELERY_RESULT_SERIALIZER = 'json'
# CELERY_WORKER_MAX_TASKS_PER_CHILD = 1000 

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# settings.py
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated'
    ],
    'DEFAULT_FRAMEWORK':{
        'DEFAULT_SCHEMA_CLASS': 'drf_spectatcular.openapi.AutoSchema'
    },
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'



# AWS S3 SETTINGS
AWS_ACCESS_KEY_ID = os.environ.get("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.environ.get("AWS_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME = os.environ.get("AWS_STORAGE_BUCKET_NAME")
AWS_S3_REGION_NAME = os.environ.get("AWS_S3_REGION_NAME")

# Tell Django to use S3 for Media (user uploads)
DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"