# Generated by Django 6.0.2 on 2026-04-12 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('media_app', '0001_initial'),
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='circle',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='transaction.circle'),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_key',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='public_url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='user_profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='account.profile'),
        ),
    ]
